// knapsack_run.h

#include <stdlib.h>
#include <stdio.h>

#ifndef KNAPSACK_RUN_H
#define KNAPSACK_RUN_H

#include "knapsack_items.h"
#include "knapsack_bag.h"

// Structure to hold metadata about a knapsack run's results:
// - Execution time and pointer to the knapsack bag generated by the algorithm.
// Access knapsack by reference for additional info (e.g. total value, items in bag, etc.)
typedef struct {
    double executionTime;       // Units are milliseconds.
    Knapsack *bag;              
} KnapsackRun;

// Structure to hold a list of knapsack run results.
// Useful for program's Experimental mode to compile results of multiple runs of a given algorithm.
typedef struct {
    size_t count;
    size_t size;
    KnapsackRun *runs;
} KnapsackRunList;

// Create knapsack run result with given execution time (ms) and knapsack bag in heap.
KnapsackRun *knapsack_run_create(double executionTime, Knapsack *bag);

// Free the memory allocated for a knapsack run result.
void knapsack_run_free(KnapsackRun *result);

// Print the result of a knapsack run on the screen.
void print_knapsack_run(const KnapsackRun *result);

// Create a new list to store Knapsack run results.
KnapsackRunList *knapsack_run_list_create(size_t listSize);

// Free the knapsack run result list and its contents.
// Also frees the knapsack bags in each run result.
void knapsack_run_list_free(KnapsackRunList *log);

// Add a new Knapsack run result entry to a Knapasck Run list.
// Returns pointer to the newly added entry, or NULL if there were errors.
KnapsackRun *knapsack_run_list_add_entry(KnapsackRunList *log, KnapsackRun newEntry);

// Get the results of a knapsack run from a list in a given index.
// Returns NULL if the index is out of bounds or if the list is NULL.
KnapsackRun *get_knapsack_run_result(const KnapsackRunList *log, size_t index);

// Get the average execution time of all knapsack runs in a list.
// Returns -1.0 if the list is NULL or empty (error state).
double get_knapsack_run_avg_execution_time(const KnapsackRunList *log);

// Check if the total value of items in two knapsack runs are equal.
// Returns true if the values are equal, false otherwise.
bool knapsack_run_total_value_match(const KnapsackRun *run1, const KnapsackRun *run2);

// Get the ratio of matching total values between two knapsack run lists.
// Returns -1.0 if either list is NULL or empty (error state).
// Returns a ratio between 0.0 and 1.0 for the number of matching runs.
double get_knapsack_runs_match_ratio(const KnapsackRunList *baseline, const KnapsackRunList *comparison);

//TODO: Add functions to output contents of knapsack run to TEX file.

#endif // KNAPSACK_RUN_H