#ifndef TEX_GENERATOR_H
#define TEX_GENERATOR_H

#include <stdio.h>
#include <stddef.h>

#include "knapsack_items.h"
#include "dynamic_programming.h"

// Create TEX file for report of Knapsack problem resolution.
FILE *tex_create_file(const char *filename);

// Initial sections of TEX file, including title and date.
void tex_gen_filename(char *buffer, size_t bufferSize);
void tex_preamble(FILE *file, const char *title);
void tex_problem(FILE *file, const ItemList *items, int capacity);

// Header section for Experimental mode's definition (e.g. number of cases, weight and item count ranges).
void tex_exp_mode_def_header(FILE *file, size_t caseCount);

// Header section for Experimental mode's statistics.
void tex_exp_mode_stats_header(FILE *file);

// DP Table for DP algorithm run.
void tex_dp_table(FILE *file, const DPKnapsackResult *dpResult, const ItemList *itemsList);

// Execution Time and contents of Knapsack generated by a specific algorithm run.
void tex_run_time(FILE *file, KnapsackRun run, const char *algorithmName);
void tex_run_contents(FILE *file, KnapsackRun run, const char *algorithmName);

// Show stats for a specific algorithm run, including execution time and knapsack contents.
void tex_dp_run_stats(FILE *file, DPKnapsackResult run, ItemList *itemsList);
void tex_greedy_run_stats(FILE *file, KnapsackRun run, bool proportional);

// Tables with aggregated results of multiple runs of Knapsack algorithms.
void tex_time_table(FILE *file, const char *title, const double results[10][10]);
void tex_accuracy_table(FILE *file, const char *title, const double results[10][10]);

// End the TEX document and close the file.
void tex_end(FILE *file);

#endif